=== mVi-Academy/LabVIEW-PurpleBook/14.数据存储与表达/TestConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="TestConfiguration">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Building" type="xs:string"/>
        <xs:element name="Lab" type="xs:string"/>
        <xs:element name="TestSetting" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Device" type="xs:string"/>
              <xs:element name="Channel" type="xs:string"/>
              <xs:element name="Samples" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== mVi-Academy/LabVIEW-PurpleBook/14.数据存储与表达/TestConfiguration.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<TestConfiguration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	   xsi:noNamespaceSchemaLocation='TestConfiguration.xsd'>
	<Building>1</Building>
	<Lab>2</Lab>
	<TestSetting>
		<Device>1</Device>
		<Channel>1</Channel>
		<Samples>20</Samples>
	</TestSetting>
	<TestSetting>
		<Device>1</Device>
		<Channel>2</Channel>
		<Samples>20</Samples>
	</TestSetting>
	<TestSetting>
		<Device>2</Device>
		<Channel>2</Channel>
		<Samples>20</Samples>
	</TestSetting>
</TestConfiguration>
